import 'server-only';
import {z} from 'zod';
import {area,distance} from '@/lib/domain';
import {ensure,rate,AppError} from '@/server/core';
import type {Place} from '@/contracts';
const feature=z.object({properties:z.object({formatted:z.string(),lat:z.number(),lon:z.number(),place_id:z.string().optional()})});
async function geo(path:string,params:Record<string,string>){ensure(process.env.GEOAPIFY_SERVER_KEY,503,'MAP_SERVICE_UNAVAILABLE','Address search and road routes are being connected. You can select your locations on the map.');await rate('geoapify-global','requests',4,1000);await rate('geoapify-global','daily',1600,86400000);const url=new URL(`https://api.geoapify.com/v1/${path}`);Object.entries({...params,apiKey:process.env.GEOAPIFY_SERVER_KEY}).forEach(([k,v])=>url.searchParams.set(k,v!));let res;try{res=await fetch(url,{signal:AbortSignal.timeout(12000),cache:'no-store'});}catch{throw new AppError(502,'ROUTE_UNAVAILABLE','The map service did not respond. Please try again.',true);}ensure(res.ok,502,'MAP_SERVICE_UNAVAILABLE','The map service is unavailable. Please try again.');return res.json();}
export async function search(q:string):Promise<Place[]>{ensure(q.length>=3&&q.length<=120,400,'INVALID_SEARCH','Enter between 3 and 120 characters.');const data=z.object({features:z.array(feature)}).parse(await geo('geocode/autocomplete',{text:q,filter:`circle:${area.center.lng},${area.center.lat},${area.radiusMeters}`,bias:`proximity:${area.center.lng},${area.center.lat}`,limit:'5'}));return data.features.map(f=>({label:f.properties.formatted.slice(0,200),lat:f.properties.lat,lng:f.properties.lon,source:'search',...(f.properties.place_id?{providerPlaceId:f.properties.place_id}:{})}));}
export async function reverse(lat:number,lng:number):Promise<Place>{let name=`Map point (${lat.toFixed(5)}, ${lng.toFixed(5)})`;try{const data=z.object({features:z.array(feature)}).parse(await geo('geocode/reverse',{lat:String(lat),lon:String(lng)}));name=data.features[0]?.properties.formatted??name;}catch{}return {label:name.slice(0,200),lat,lng,source:'pin'};}
export async function route(pickup:Place,destination:Place){ensure(distance(pickup,area.center)<=area.radiusMeters&&distance(destination,area.center)<=area.radiusMeters,422,'OUTSIDE_SERVICE_AREA','Both locations must be within 25 km of central Bengaluru.');ensure(distance(pickup,destination)>=200,422,'LOCATIONS_TOO_CLOSE','Choose locations at least 200 metres apart.');
 if(process.env.APP_ENV==='test'&&process.env.FIRESTORE_EMULATOR_HOST&&process.env.TEST_PROVIDER_FIXTURES==='true'&&!process.env.VERCEL)return {distanceMeters:5000,durationSeconds:900,routeGeometry:{type:'LineString' as const,coordinates:[[pickup.lng,pickup.lat],[destination.lng,destination.lat]]}};
 const data=z.object({features:z.array(z.object({properties:z.object({distance:z.number().min(200).max(200000),time:z.number().min(1).max(86400)}),geometry:z.object({type:z.literal('MultiLineString'),coordinates:z.array(z.array(z.tuple([z.number(),z.number()])))})}))}).parse(await geo('routing',{waypoints:`${pickup.lat},${pickup.lng}|${destination.lat},${destination.lng}`,mode:'drive'}));const f=data.features[0];ensure(f,502,'NO_ROUTE','No road route was found between these locations.');const coordinates=f.geometry.coordinates.flat();const step=Math.max(1,Math.ceil(coordinates.length/4998));return {distanceMeters:Math.round(f.properties.distance),durationSeconds:Math.round(f.properties.time),routeGeometry:{type:'LineString' as const,coordinates:coordinates.filter((_,i)=>i%step===0||i===coordinates.length-1)}};
}
